name: CI Build

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: CI Build

    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"

      - name: Generate test report
        uses: bibipkins/dotnet-test-reporter@v1.4.1
        if: ${{ always() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: 'Test Results'
          results-path: tests/MotionExtract.Tests/**/*.trx
          coverage-path: tests/MotionExtract.Tests/**/*.cobertura.xml
          coverage-type: cobertura
          coverage-threshold: 70

      - name: Publish
        run: dotnet publish src/MotionExtract/MotionExtract.csproj --runtime "${{ matrix.target }}" -c Debug